# Generated by Django 2.1.3 on 2018-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('userPassword', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('loginNum', models.CharField(default='0', max_length=32)),
                ('userCreat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
