# Generated by Django 2.1.3 on 2018-12-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0002_auto_20181224_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('bookID', models.CharField(max_length=32)),
                ('platform', models.EmailField(max_length=32)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
