# Generated by Django 2.1.3 on 2018-12-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0004_auto_20181228_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='price',
            field=models.CharField(default=-1, max_length=32),
        ),
    ]
