# Generated by Django 2.1.3 on 2018-12-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0006_auto_20181228_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='bookname',
            field=models.EmailField(default='wu', max_length=100),
        ),
    ]
