# Generated by Django 2.1.3 on 2018-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0007_booklist_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='bookname',
            field=models.EmailField(max_length=100),
        ),
    ]
